fix: downgrade pyyaml <6.0
Latest cython 3.0 breaks pyYAML 6.0. Installation fails with:
AttributeError: cython_sources

Cython 3.0 is in beta at the moment and this needs to be fixed upstream.

Signed-off-by: Moritz Johner <beller.moritz@googlemail.com>