fix: bump codeqls together (#6707)
codeql bumps of dependabot are independent.

It leads to issue of version mismatch like this:L

Error: Loaded a configuration file for version '4.37.3',
but running version '4.36.3'.

To fix that, let's ensure init and analyse are bundled
together, through a dependabot group.

Example errors:
[1]: https://github.com/external-secrets/external-secrets/pull/6666
[2]: https://github.com/external-secrets/external-secrets/pull/6668

Signed-off-by: Jean-Philippe Evrard <jean-philippe.evrard+rochepub@external.roche.com>
Co-authored-by: Gergely Bräutigam <gergely.brautigam@sap.com>